version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: "postgresql://postgres:postgres@postgres:5432/csgo"
      REDIS_URL: "redis://redis:6379"
      MONGO_URL: "mongodb://root:example@mongo:27017"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: csgo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./db/mongo_init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  postgres_data:
  redis_data:
  mongo_data: